/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyMeasurement {
  'rightThigh' : number,
  'leftThigh' : number,
  'date' : string,
  'hips' : number,
  'chest' : number,
  'rightBicep' : number,
  'waist' : number,
  'leftBicep' : number,
}
export interface FitnessClassView {
  'id' : bigint,
  'enrolled' : Array<Principal>,
  'date' : string,
  'name' : string,
  'description' : string,
  'zoomLink' : [] | [string],
  'capacity' : bigint,
}
export type Gender = { 'female' : null } |
  { 'male' : null };
export interface MealLog {
  'date' : string,
  'note' : string,
  'imageUrl' : [] | [string],
  'mealType' : string,
}
export interface Promotion {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'imageUrl' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'gender' : Gender }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightLogEntry {
  'weight' : number,
  'date' : string,
  'absent' : boolean,
}
export interface ActivityComment {
  'activityKey' : string,
  'comment' : string,
  'createdAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<
    [string, string, string, bigint, [] | [string]],
    bigint
  >,
  'createPromotion' : ActorMethod<[string, string, [] | [string]], bigint>,
  'deleteClass' : ActorMethod<[bigint], undefined>,
  'deletePromotion' : ActorMethod<[bigint], undefined>,
  'enrollInClass' : ActorMethod<[bigint], undefined>,
  'getAllPromotions' : ActorMethod<[], Array<Promotion>>,
  'getAllUserMealLogs' : ActorMethod<[Principal, string], Array<MealLog>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[bigint], [] | [FitnessClassView]>,
  'getMeasurementLogs' : ActorMethod<
    [Principal],
    [] | [Array<BodyMeasurement>]
  >,
  'getTodayMealLogs' : ActorMethod<[string], Array<MealLog>>,
  'getUpcomingClasses' : ActorMethod<[], Array<FitnessClassView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightLogs' : ActorMethod<[Principal], [] | [Array<WeightLogEntry>]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMeasurements' : ActorMethod<
    [string, number, number, number, number, number, number, number],
    undefined
  >,
  'logWeight' : ActorMethod<[string, number], undefined>,
  'logWeightAbsent' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMealLog' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'saveActivityComment' : ActorMethod<[Principal, string, string], undefined>,
  'getActivityComments' : ActorMethod<[Principal], Array<ActivityComment>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];