/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Promotion = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FitnessClassView = IDL.Record({
  'id' : IDL.Nat,
  'enrolled' : IDL.Vec(IDL.Principal),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const BodyMeasurement = IDL.Record({
  'rightThigh' : IDL.Float64,
  'leftThigh' : IDL.Float64,
  'date' : IDL.Text,
  'hips' : IDL.Float64,
  'chest' : IDL.Float64,
  'rightBicep' : IDL.Float64,
  'waist' : IDL.Float64,
  'leftBicep' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createPromotion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'enrollInClass' : IDL.Func([IDL.Nat], [], []),
  'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(FitnessClassView)], ['query']),
  'getMeasurementLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(BodyMeasurement))],
      ['query'],
    ),
  'getUpcomingClasses' : IDL.Func([], [IDL.Vec(FitnessClassView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightLogs' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Vec(IDL.Record({ 'weight' : IDL.Float64, 'date' : IDL.Text }))
        ),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMeasurements' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Promotion = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FitnessClassView = IDL.Record({
    'id' : IDL.Nat,
    'enrolled' : IDL.Vec(IDL.Principal),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const BodyMeasurement = IDL.Record({
    'rightThigh' : IDL.Float64,
    'leftThigh' : IDL.Float64,
    'date' : IDL.Text,
    'hips' : IDL.Float64,
    'chest' : IDL.Float64,
    'rightBicep' : IDL.Float64,
    'waist' : IDL.Float64,
    'leftBicep' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createPromotion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'enrollInClass' : IDL.Func([IDL.Nat], [], []),
    'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(FitnessClassView)], ['query']),
    'getMeasurementLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(BodyMeasurement))],
        ['query'],
      ),
    'getUpcomingClasses' : IDL.Func([], [IDL.Vec(FitnessClassView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightLogs' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Vec(IDL.Record({ 'weight' : IDL.Float64, 'date' : IDL.Text }))
          ),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMeasurements' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };