/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Promotion = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const MealLog = IDL.Record({
  'date' : IDL.Text,
  'note' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'mealType' : IDL.Text,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'gender' : Gender });
export const FitnessClassView = IDL.Record({
  'id' : IDL.Nat,
  'enrolled' : IDL.Vec(IDL.Principal),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'zoomLink' : IDL.Opt(IDL.Text),
  'capacity' : IDL.Nat,
});
export const BodyMeasurement = IDL.Record({
  'rightThigh' : IDL.Float64,
  'leftThigh' : IDL.Float64,
  'date' : IDL.Text,
  'hips' : IDL.Float64,
  'chest' : IDL.Float64,
  'rightBicep' : IDL.Float64,
  'waist' : IDL.Float64,
  'leftBicep' : IDL.Float64,
});
export const WeightLogEntry = IDL.Record({
  'weight' : IDL.Float64,
  'date' : IDL.Text,
  'absent' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createPromotion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteClass' : IDL.Func([IDL.Nat], [], []),
  'deletePromotion' : IDL.Func([IDL.Nat], [], []),
  'enrollInClass' : IDL.Func([IDL.Nat], [], []),
  'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getAllUserMealLogs' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(MealLog)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(FitnessClassView)], ['query']),
  'getMeasurementLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(BodyMeasurement))],
      ['query'],
    ),
  'getTodayMealLogs' : IDL.Func([IDL.Text], [IDL.Vec(MealLog)], ['query']),
  'getUpcomingClasses' : IDL.Func([], [IDL.Vec(FitnessClassView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(WeightLogEntry))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMeasurements' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'logWeightAbsent' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMealLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Promotion = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const MealLog = IDL.Record({
    'date' : IDL.Text,
    'note' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'mealType' : IDL.Text,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'gender' : Gender });
  const FitnessClassView = IDL.Record({
    'id' : IDL.Nat,
    'enrolled' : IDL.Vec(IDL.Principal),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'zoomLink' : IDL.Opt(IDL.Text),
    'capacity' : IDL.Nat,
  });
  const BodyMeasurement = IDL.Record({
    'rightThigh' : IDL.Float64,
    'leftThigh' : IDL.Float64,
    'date' : IDL.Text,
    'hips' : IDL.Float64,
    'chest' : IDL.Float64,
    'rightBicep' : IDL.Float64,
    'waist' : IDL.Float64,
    'leftBicep' : IDL.Float64,
  });
  const WeightLogEntry = IDL.Record({
    'weight' : IDL.Float64,
    'date' : IDL.Text,
    'absent' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createPromotion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteClass' : IDL.Func([IDL.Nat], [], []),
    'deletePromotion' : IDL.Func([IDL.Nat], [], []),
    'enrollInClass' : IDL.Func([IDL.Nat], [], []),
    'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getAllUserMealLogs' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(MealLog)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(FitnessClassView)], ['query']),
    'getMeasurementLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(BodyMeasurement))],
        ['query'],
      ),
    'getTodayMealLogs' : IDL.Func([IDL.Text], [IDL.Vec(MealLog)], ['query']),
    'getUpcomingClasses' : IDL.Func([], [IDL.Vec(FitnessClassView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(WeightLogEntry))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMeasurements' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'logWeight' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'logWeightAbsent' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMealLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };