/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyMeasurement {
  'rightThigh' : number,
  'leftThigh' : number,
  'date' : string,
  'hips' : number,
  'chest' : number,
  'rightBicep' : number,
  'waist' : number,
  'leftBicep' : number,
}
export interface FitnessClassView {
  'id' : bigint,
  'enrolled' : Array<Principal>,
  'date' : string,
  'name' : string,
  'description' : string,
  'capacity' : bigint,
}
export interface Promotion {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<[string, string, string, bigint], bigint>,
  'createPromotion' : ActorMethod<[string, string], bigint>,
  'enrollInClass' : ActorMethod<[bigint], undefined>,
  'getAllPromotions' : ActorMethod<[], Array<Promotion>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[bigint], [] | [FitnessClassView]>,
  'getMeasurementLogs' : ActorMethod<
    [Principal],
    [] | [Array<BodyMeasurement>]
  >,
  'getUpcomingClasses' : ActorMethod<[], Array<FitnessClassView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightLogs' : ActorMethod<
    [Principal],
    [] | [Array<{ 'weight' : number, 'date' : string }>]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMeasurements' : ActorMethod<
    [string, number, number, number, number, number, number, number],
    undefined
  >,
  'logWeight' : ActorMethod<[string, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];